apiVersion: v2
name: loki
version: 0.1.0
description: "Loki deployment for log aggregation"
type: application
dependencies:
  - name: loki
    repository: https://grafana.github.io/helm-charts
    version: 6.22.0
