apiVersion: v2
name: external-dns
description: A Helm chart for Cert Manager
type: application
version: 1.0.0
dependencies:
  - name: cert-manager
    version: v1.19.1
    repository: https://charts.jetstack.io