apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-argo
  namespace: {{ .Release.Namespace }}
spec:
  hostnames:
  - argo.schober.dev
  parentRefs:
    - kind: Gateway
      name: internal-gateway
      namespace: istio-ingress-internal
  rules:
    - backendRefs:
        - name: argocd-server
          port: 443