apiVersion: v2
name: n8n
description: "n8n deployment for homelab"
type: application
version: 0.1.0
dependencies:
  - name: n8n
    version: 2.0.1
    repository: oci://8gears.container-registry.com/library
