apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey-auth
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: valkey-auth
  data:
    - secretKey: valkey-password
      remoteRef:
        key: valkey-password
