apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  hostnames:
  - prometheus.schober.dev
  parentRefs:
    - kind: Gateway
      name: internal-gateway
      namespace: istio-ingress-internal
      sectionName: https
  rules:
    - backendRefs:
        - name: prometheus-server
          port: 80
