apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-authentik-oidc
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: argocd-authentik-oidc
  data:
    - secretKey: dex.authentik.clientSecret
      remoteRef:
        key: argocd-authentik-client-secret
