apiVersion: v2
name: argo
version: 0.1.0
description: "Upstream Argo CD deployment"
type: application
dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 9.1.0
