apiVersion: v2
name: argo-config
version: 0.1.0
description: "Config objects for ArgoCD"
type: application
dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 9.1.0
