apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-zot
  namespace: {{ .Release.Namespace }}
spec:
  hostnames:
    - zot.schober.dev
  parentRefs:
    - kind: Gateway
      name: internal-gateway
      namespace: istio-ingress-internal
      sectionName: https
  rules:
    - backendRefs:
        - name: zot
          port: 5000
