apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zot-oidc-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: zot-oidc-credentials
    template:
      type: Opaque
      engineVersion: v2
      data:
        oidc-credentials.json: |
          {
            "clientid": "{{ .clientId }}",
            "clientsecret": "{{ .clientSecret }}"
          }
  data:
    - secretKey: clientid
      remoteRef:
        key: zot-oidc-client-id
    - secretKey: clientsecret
      remoteRef:
        key: zot-oidc-client-secret
