apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zot-oidc-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: zot-oidc-credentials
  data:
    - secretKey: clientid
      remoteRef:
        key: zot-oidc-clientid
    - secretKey: clientsecret
      remoteRef:
        key: zot-oidc-clientsecret