apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-authentik-oidc
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: grafana-authentik-oidc
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: grafana
  data:
    - secretKey: GRAFANA_OAUTH_CLIENT_SECRET
      remoteRef:
        key: authentik-grafana-client-secret
