apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-grafana
  namespace: {{ .Release.Namespace }}
spec:
  hostnames:
  - grafana.schober.dev
  parentRefs:
    - kind: Gateway
      name: internal-gateway
      namespace: istio-ingress-internal
      sectionName: https
  rules:
    - backendRefs:
        - name: grafana
          port: 80
