apiVersion: v2
name: external-dns
description: A Helm chart for External DNS
type: application
version: 1.0.0
dependencies:
  - name: external-dns
    version: 1.19.0
    repository: https://kubernetes-sigs.github.io/external-dns/