apiVersion: v2
name: cilium
description: A Helm chart for Headlamp
type: application
version: 1.0.0
dependencies:
  - name: headlamp
    version: 0.31.1
    repository: https://kubernetes-sigs.github.io/headlamp/