apiVersion: v2
name: authentik
description: "Authentik deployment"
type: application
version: 0.1.0
dependencies:
  - name: authentik
    repository: https://charts.goauthentik.io
    version: 2025.12.4
