{{- $externalSecret := default dict .Values.externalSecret -}}
{{- if (default false (get $externalSecret "enabled")) }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ default "1h" (get $externalSecret "refreshInterval") }}
  secretStoreRef:
    name: {{ default "bitwarden" (get (default dict (get $externalSecret "secretStoreRef")) "name") }}
    kind: {{ default "ClusterSecretStore" (get (default dict (get $externalSecret "secretStoreRef")) "kind") }}
  target:
    name: mealie-secret
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: {{ default "mealie-secret-key" (get (default dict (get $externalSecret "keys")) "secretKey") | quote }}
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: {{ default "authentik-mealie-client-secret" (get (default dict (get $externalSecret "keys")) "oidcClientSecret") | quote }}
{{- end }}
