external-secrets:
  crds:
    createClusterGenerator: false
    createClusterPushSecret: false
  bitwarden-sdk-server:
    enabled: true
  namespaceOverride: "external-secrets"
  image:
    tls:
      enabled: true
      volumeMounts:
        - mountPath: "/certs"
          name: "bitwarden-tls-certs"
      volumes:
        - name: "bitwarden-tls-certs"
          secret:
            secretName: "bitwarden-tls-certs"
            items:
              - key: "tls.crt"
                path: "cert.pem"
              - key: "tls.key"
                path: "key.pem"
              - key: "ca.crt"
                path: "ca.pem"