apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
  namespace: {{ .Release.Namespace }}
spec:
  instances: 1

  storage:
    size: 1Gi
    storageClass: proxmox-csi

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
    recovery:
      volumeSnapshots:
        storage:
          kind: PersistentVolumeClaim
          name: authentik-postgres

