{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: authentik-secret
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: {{ .Values.externalSecret.data.secretKey | quote }}
    {{- if .Values.externalSecret.data.bootstrapPassword }}
    - secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.data.bootstrapPassword | quote }}
    {{- end }}
    {{- if .Values.externalSecret.data.bootstrapEmail }}
    - secretKey: AUTHENTIK_BOOTSTRAP_EMAIL
      remoteRef:
        key: {{ .Values.externalSecret.data.bootstrapEmail | quote }}
    {{- end }}
    {{- if .Values.externalSecret.data.bootstrapToken }}
    - secretKey: AUTHENTIK_BOOTSTRAP_TOKEN
      remoteRef:
        key: {{ .Values.externalSecret.data.bootstrapToken | quote }}
    {{- end }}
    - secretKey: argocdClientSecret
      remoteRef:
        key: argocd-authentik-client-secret
    - secretKey: grafanaClientSecret
      remoteRef:
        key: {{ .Values.externalSecret.data.grafanaClientSecret | quote }}
    - secretKey: mealieClientSecret
      remoteRef:
        key: {{ .Values.externalSecret.data.mealieClientSecret | quote }}
{{- end }}
