{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: n8n-secret
  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: {{ .Values.externalSecret.keys.encryption | quote }}
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.keys.redisPassword | quote }}
{{- end }}
