apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: {{ .Release.Namespace }}
  labels:
    istio.io/use-waypoint: demo-app-waypoint
spec:
  selector:
    app: nginx-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
