apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: demo-app-waypoint
  namespace: {{ .Release.Namespace }}
  labels:
    istio.io/waypoint-for: demo-app
spec:
  gatewayClassName: istio-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
