apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: bitwarden
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    bitwardensecretsmanager:
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            key: token
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      organizationID: 885fbdef-f939-4932-87b4-b38b0120ce52
      projectID: 83186dfc-0604-4260-b0ec-b38d0160e6cd
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: ca.crt