apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden-test-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: SecretStore
  data:
    - secretKey: test
      remoteRef:
        key: "test"