apiVersion: v2
name: mimir
version: 0.1.0
description: "Mimir deployment for metrics storage"
type: application
dependencies:
  - name: mimir-distributed
    repository: https://grafana.github.io/helm-charts
    version: 5.6.0
