namespaces:
  - name: default
    labels:
      istio.io/dataplane-mode: ambient
  - name: istio-system
    labels:
      pod-security.kubernetes.io/enforce: privileged
  - name: istio-ingress-internal
    labels:
      istio.io/dataplane-mode: ambient
  - name: argocd
  - name: management
    labels:
      istio.io/dataplane-mode: ambient
