namespaces:
  - name: istio-system
    labels:
      pod-security.kubernetes.io/enforce: privileged
  - name: istio-ingress
    labels:
      istio-injection: "enabled"
      pod-security.kubernetes.io/enforce: privileged
  - name: argocd