namespaces:
  - name: default
    labels:
      istio.io/dataplane-mode: ambient
  - name: istio-system
    labels:
      pod-security.kubernetes.io/enforce: privileged
  - name: istio-ingress-internal
    labels:
      istio.io/dataplane-mode: ambient
  - name: argocd
  - name: external-dns
    labels:
      istio.io/dataplane-mode: ambient
  - name: cert-manager
    labels:
      istio.io/dataplane-mode: ambient
  - name: external-secrets
  - name: monitoring
    labels:
      istio.io/dataplane-mode: ambient
      pod-security.kubernetes.io/enforce: privileged
