apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: schober-dev-tls
  namespace: {{ .Release.Namespace }}
spec:
  issuerRef:
    name: cloudflare-letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "*.schober.dev"
  secretName: schober-dev-tls