apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-letsencrypt
spec:
  gatewayClassName: istio
  listeners:
    - hostname: "*.schober.dev"
      name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: schober-dev-tls
            kind: Secret
            namespace: {{ .Release.Namespace }}
            group: ""