apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: {{ .Release.Namespace }}
spec:
  tracing:
    - providers:
        - name: alloy-otlp
      randomSamplingPercentage: 100.0
  accessLogging:
    - providers:
        - name: alloy-otlp
