{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.paperless.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.paperless.secretName }}
  data:
    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: {{ .Values.externalSecret.keys.secretKey | quote }}
    - secretKey: PAPERLESS_DBPASS
      remoteRef:
        key: {{ .Values.externalSecret.keys.dbPassword | quote }}
    - secretKey: PAPERLESS_REDIS
      remoteRef:
        key: {{ .Values.externalSecret.keys.redisUrl | quote }}
    {{- with .Values.externalSecret.keys.adminUser }}
    - secretKey: PAPERLESS_ADMIN_USER
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.externalSecret.keys.adminPassword }}
    - secretKey: PAPERLESS_ADMIN_PASSWORD
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.externalSecret.keys.adminMail }}
    - secretKey: PAPERLESS_ADMIN_MAIL
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
{{- end }}
