{{- if .Values.tika.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: paperless-tika
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: paperless
    component: tika
  ports:
    - protocol: TCP
      port: 9998
      targetPort: 9998
{{- end }}
