apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bitwarden-bootstrap-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  # renamed to avoid collision with server cert secret
  name: bitwarden-ca
  namespace: {{ .Release.Namespace }}
spec:
  # Root CA certificate used to sign Bitwarden server and client certs
  commonName: bitwarden-ca
  isCA: true
  secretName: bitwarden-ca-secret
  subject:
    organizations:
      - external-secrets.io
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
    rotationPolicy: Always
  issuerRef:
    name: bitwarden-bootstrap-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bitwarden-certificate-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    # Updated to use the dedicated CA secret instead of sharing the server cert secret
    secretName: bitwarden-ca-secret
