proxmox-csi-plugin:
  existingConfigSecret:
    name: proxmox-csi-plugin

  node:
    nodeSelector:
      node.cloudprovider.kubernetes.io/platform: nocloud
    tolerations:
      - operator: Exists

  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule

  storageClass:
    - name: proxmox-csi
      storage: local-lvm
      reclaimPolicy: Retain
      fstype: ext4
      cache: writethrough
      ssd: "true"
      mountOptions:
        - noatime
