proxmox-csi-plugin:
  config:
    clusters:
      - url: https://cluster-api-1.exmple.com:8006/api2/json
        insecure: false
        token_id: "kubernetes-csi@pve!csi"
        token_secret: "key"
        region: cluster-1

  node:
    nodeSelector:
      node.cloudprovider.kubernetes.io/platform: nocloud
    tolerations:
      - operator: Exists

  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule

  storageClass:
    - name: proxmox-csi
      storage: local-lvm
      reclaimPolicy: Retain
      fstype: ext4
      cache: writethrough
      ssd: "true"
