apiVersion: v2
name: grafana
version: 0.1.0
description: "Grafana deployment for monitoring"
type: application
dependencies:
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 8.8.2
