cert-manager:
  crds:
    enabled: true
  featureGates: "ExperimentalGatewayAPISupport=true"
  extraArgs:
    - --enable-certificate-owner-ref=true
    - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53
    - --dns01-recursive-nameservers-only
    - --dns01-check-retry-period=10s
